apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-share
spec:
  capacity:
    storage: 256M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.10.2.2
    path: /export/data
