apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
