apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-iphyton-master
  labels:
    app: jupyter-iphyton-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-iphyton-master
  template:
    metadata:
      labels:
        app: jupyter-iphyton-master
    spec:
    # running as root because of user jovyan
      securityContext:
        runAsUser: 0
      containers:
      - name: jupyter-iphyton-master
        image: dalvez/jupyter-tensorflow-ipyparallel:latest
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8888
        command: ["/bin/bash","-c","ipcontroller --ip=$(POD_IP) --location=jupyter-iphyton-master --profile-dir=/home/jovyan/work/ && start-notebook.sh --NotebookApp.token=''"]
      #  args: ["ipcontroller --ip=$(POD_IP) --location=jupyter-iphyton-master --profile-dir=/home/jovyan/work/;start-notebook.sh --NotebookApp.token=''"]
      #  args: ["ipcontroller --ip=$(POD_IP) --location=jupyter-iphyton-master --profile-dir=/home/jovyan/work/"]
        volumeMounts:
        - name: iphyton-profile-volume
          mountPath: /home/jovyan/work
      volumes:
      - name: iphyton-profile-volume
        persistentVolumeClaim:
         claimName: pvc
