kind: Service
apiVersion: v1
metadata:
  name: jupyter-iphyton-master
spec:
  type: NodePort
  selector:
    app: jupyter-iphyton-master
  ports:
  - protocol: TCP
    nodePort: 30040
    port: 8888
    targetPort: 8888
