apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-share
spec:
  capacity:
    storage: 16M # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below
  nfs:
    server: 10.10.2.2 # Please change this to your NFS server
    path: /export/data # Please change this to the relevant share
