apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-iphyton-node
  labels:
    app: jupyter-iphyton-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-iphyton-node
  template:
    metadata:
      labels:
        app: jupyter-iphyton-node
    spec:
    #  securityContext:
    #    runAsUser: 0
      containers:
      - name: jupyter-iphyton-node
        image: dalvez/jupyter-ipyparallel-kubectl:latest
        imagePullPolicy: Always
    #   env:
    #   - name: GRANT_SUDO
    #     value: "yes"
    #    ports:
    #    - containerPort: 8888
        command: ["/bin/bash","-c","ipengine --profile-dir=/home/jupyter/work --log-to-file --log-level=DEBUG"]
    #   args: ["ipengine --profile-dir=/home/jupyter/work"]
        volumeMounts:
        - name: iphyton-profile-volume
          mountPath: /home/jupyter/work
      volumes:
      - name: iphyton-profile-volume
        persistentVolumeClaim:
         claimName: pvc
