FROM ubuntu:18.04

LABEL maintainer="David Alvez <dalvez@inf.upv.es>"

RUN apt-get update && apt-get install -y python3 \
    python3-pip \
    apt-transport-https \
    sudo \
    curl

#Kubectl repo for Ubuntu Bionic still not available (11.05.2019)
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
RUN echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list

RUN apt-get update && apt-get install -y kubectl

RUN pip3 install jupyter

RUN pip3 install ipyparallel

RUN useradd -ms /bin/bash jupyter

RUN adduser jupyter sudo

RUN echo 'jupyter ALL=NOPASSWD: ALL' >> /etc/sudoers

USER jupyter

WORKDIR /home/jupyter

RUN mkdir -p /home/jupyter/work

COPY ./scripts/start.sh /usr/local/bin

COPY ./scripts/scale.sh /usr/local/bin

USER root

RUN chown jupyter /usr/local/bin/start.sh

RUN chown jupyter /usr/local/bin/scale.sh

RUN chmod +x /usr/local/bin/start.sh

RUN chmod +x /usr/local/bin/scale.sh

USER jupyter

ENTRYPOINT ["start.sh"]

#ENTRYPOINT ["jupyter", "notebook", "--ip=0.0.0.0", "--NotebookApp.token=''"]
