FROM ubuntu:18.04

LABEL maintainer="David Alvez <dalvez@inf.upv.es>"

RUN apt-get update && apt-get install -y python3 \
    python3-pip

RUN pip3 install ipyparallel

RUN useradd -ms /bin/bash jupyter

USER jupyter

WORKDIR /home/jupyter

RUN mkdir -p /home/jupyter/work

USER jupyter

ENTRYPOINT ["ipengine --profile-dir=/home/jupyter/work --log-to-file --log-level=DEBUG"]
